# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
# From decision table
# "../SynData/lfet/ItemBuilderEngine.lfet"
# 03.02.2026 13:23
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#
# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from faker import Faker
from de_DE.item_builder_engine_germany import ItemBuilderEngineGermany
from common.item_builder_engine_faker import ItemBuilderEngineFaker
import SynData

class ItemBuilderEngine:

    def execute(self, instance: SynData, localization: str, keyword: str, item: str, item_data: dict):
        # Prolog Decision Table <----
        # Condition B01/01: Current Mode / DEF / The default mode, in which random data is to be generated.
        if ( instance.MODE_DEF == instance.get_mode() ):
            # Condition B02/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):
                # Condition B04/01: Localization / de_DE / Germany
                if ( "de_DE" == localization ):
                    # Rule R01 ---->
                    # Action A01/02: Call ItemBuilderEngine... / Germany / This item builder is responsible for german test data.
                    retval = ItemBuilderEngineGermany.execute(instance, localization, item, item_data)
                    # Action A02/01: Call for logging / local / The locally generated value should be transferred to the logging
                    instance.add_log_entry(keyword, item, retval)
                    # Action A04: Return date from ItemBuilderEngine...
                    return retval
                    # Rule R01 <----
                else:
                    # Rule R02 ---->
                    # Action A01/01: Call ItemBuilderEngine... / Faker / If there is no reliable implementation for the defined localization, Faker is used as a substitute.
                    retval = ItemBuilderEngineFaker.execute(instance, localization, item, item_data)
                    # Action A02/01: Call for logging / local / The locally generated value should be transferred to the logging
                    instance.add_log_entry(keyword, item, retval)
                    # Action A04: Return date from ItemBuilderEngine...
                    return retval
                    # Rule R02 <----
            else:
                # Condition B03/01: Requested item is / unknown / The requested item has not yet been created within the context.
                if ( None == instance.get_item(item) ):
                    # Condition B04/01: Localization / de_DE / Germany
                    if ( "de_DE" == localization ):
                        # Rule R03 ---->
                        # Action A01/02: Call ItemBuilderEngine... / Germany / This item builder is responsible for german test data.
                        retval = ItemBuilderEngineGermany.execute(instance, localization, item, item_data)
                        # Action A02/02: Call for logging / stored / The value should be read from the data structure for logging.
                        value = instance.get_item(item)
                        instance.add_log_entry(keyword, item, value)
                        # Action A04: Return date from ItemBuilderEngine...
                        return retval
                        # Rule R03 <----
                    else:
                        # Rule R04 ---->
                        # Action A01/01: Call ItemBuilderEngine... / Faker / If there is no reliable implementation for the defined localization, Faker is used as a substitute.
                        retval = ItemBuilderEngineFaker.execute(instance, localization, item, item_data)
                        # Action A02/02: Call for logging / stored / The value should be read from the data structure for logging.
                        value = instance.get_item(item)
                        instance.add_log_entry(keyword, item, value)
                        # Action A04: Return date from ItemBuilderEngine...
                        return retval
                        # Rule R04 <----
                else:
                    # Rule R05 ---->
                    # Action A02/02: Call for logging / stored / The value should be read from the data structure for logging.
                    value = instance.get_item(item)
                    instance.add_log_entry(keyword, item, value)
                    # Action A03: Return of data stored in the current context
                    return instance.get_item(item)
                    # Rule R05 <----
        else:
            # Rule R06 ---->
            # Action A05: Not Implemented Yet
            pass
            # Rule R06 <----

# End of generated Python source code
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
