# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
# From decision table
# "E:/data/schweier/rbtfrmwrk/SynData/lfet/ItemBuilderEngine.lfet"
# 28.01.2026 14:47
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#

# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from faker import Faker
from de_DE.person import Person
import SynData

class ItemBuilderEngine:

    def execute(self, instance: SynData, localization: str, item: str, item_data: dict):

        # Prolog Decision Table <----

        _item_builder_engine_rule_executed: bool = False

        # Condition B01/01: Current Mode / DEF / The default mode, in which random data is to be generated.
        if ( instance.MODE_DEF == instance.get_mode() ):

            # Condition B02/01: Context is / None / There is no set context.
            if ( None == instance.Get_Context() ):

                # Condition B04/01: Localization / de / German
                if ( "de_DE" == localization ):

                    # Condition B05/01: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
                    if ( "person.name" == item ):
                        # Rule R01 ---->

                        _item_builder_engine_rule_executed = True

                        # Action A01/01: Creating data with de_Provider / person.name /
                        return Person.get_name(item_data)

                        # Rule R01 <----

                    # Condition B05/02: Requestes item code / person.first_name / A first name should be returned.
                    elif ( "person.first_name" == item ):
                        # Rule R02 ---->

                        _item_builder_engine_rule_executed = True

                        # Action A01/02: Creating data with de_Provider / person.first_name /
                        return Person.get_first_name(item_data)

                        # Rule R02 <----

                    # Condition B05/03: Requestes item code / person.last_name / A last name should be returned.
                    elif ( "person.last_name" == item ):
                        # Rule R03 ---->

                        _item_builder_engine_rule_executed = True

                        # Action A01/03: Creating data with de_Provider / person.last_name /
                        return Person.get_last_name(item_data)

                        # Rule R03 <----
                else:

                    # Condition B05/01: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
                    if ( "person.name" == item ):
                        # Rule R04 ---->

                        _item_builder_engine_rule_executed = True

                        # Action A03/01: Creating data with Faker / person.name /
                        fake = Faker(localization)
                        match item_data.get("sex"):
                            case "f":
                                return fake.name_female()
                            case "m":
                                return fake.name_male()
                            case "d":
                                return fake.name_nonbinary()
                            case _:
                                return fake.name()

                        # Rule R04 <----

                    # Condition B05/02: Requestes item code / person.first_name / A first name should be returned.
                    elif ( "person.first_name" == item ):
                        # Rule R05 ---->

                        _item_builder_engine_rule_executed = True

                        # Action A03/02: Creating data with Faker / person.first_name /
                        fake = Faker(localization)
                        match item_data.get("sex"):
                            case "f":
                                return fake.first_name_female()
                            case "m":
                                return fake.first_name_male()
                            case "d":
                                return fake.first_name_nonbinary()
                            case _:
                                return fake.first_name()

                        # Rule R05 <----

                    # Condition B05/03: Requestes item code / person.last_name / A last name should be returned.
                    elif ( "person.last_name" == item ):
                        # Rule R06 ---->

                        _item_builder_engine_rule_executed = True

                        # Action A03/03: Creating data with Faker / person.last_name /
                        fake = Faker(localization)
                        match item_data.get("sex"):
                            case "f":
                                return fake.last_name_female()
                            case "m":
                                return fake.last_name_male()
                            case "d":
                                return fake.last_name_nonbinary()
                            case _:
                                return fake.last_name()

                        # Rule R06 <----
            else:

                # Condition B03/01: Requested item is / unknown / The requested item has not yet been created within the context.
                if ( None == instance.get_item(item) ):

                    # Condition B04/01: Localization / de / German
                    if ( "de_DE" == localization ):

                        # Condition B05/01: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
                        if ( "person.name" == item ):

                            # Condition B06/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                            if ( None == instance.get_item("person.first_name") ):

                                # Condition B07/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                                if ( None == instance.get_item("person.last_name") ):
                                    # Rule R07 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A02/01: Creating data with de_Provider and saving in current context / person.name /

                                    instance.add_item("person.first_name", Person.get_first_name(item_data))
                                    instance.add_item("person.last_name", Person.get_last_name(item_data))
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R07 <----
                                else:
                                    # Rule R08 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A02/02: Creating data with de_Provider and saving in current context / person.first_name /
                                    instance.add_item(item, Person.get_first_name(item_data))

                                    # Action A05: Calculate person.name  from stored individual values
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R08 <----
                            else:

                                # Condition B07/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                                if ( None == instance.get_item("person.last_name") ):
                                    # Rule R09 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A02/03: Creating data with de_Provider and saving in current context / person.last_name /
                                    instance.add_item(item, Person.get_last_name(item_data))

                                    # Action A05: Calculate person.name  from stored individual values
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R09 <----
                                else:
                                    # Rule R10 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A05: Calculate person.name  from stored individual values
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R10 <----

                        # Condition B05/02: Requestes item code / person.first_name / A first name should be returned.
                        elif ( "person.first_name" == item ):
                            # Rule R11 ---->

                            _item_builder_engine_rule_executed = True

                            # Action A02/01: Creating data with de_Provider and saving in current context / person.name /

                            instance.add_item("person.first_name", Person.get_first_name(item_data))
                            instance.add_item("person.last_name", Person.get_last_name(item_data))
                            first_name = instance.get_item("person.first_name")
                            last_name = instance.get_item("person.last_name")
                            instance.add_item("person.name", f"{first_name} {last_name}")

                            # Action A06: Return of data stored in the current context
                            return instance.get_item(item)

                            # Rule R11 <----

                        # Condition B05/03: Requestes item code / person.last_name / A last name should be returned.
                        elif ( "person.last_name" == item ):
                            # Rule R12 ---->

                            _item_builder_engine_rule_executed = True

                            # Action A02/03: Creating data with de_Provider and saving in current context / person.last_name /
                            instance.add_item(item, Person.get_last_name(item_data))

                            # Action A06: Return of data stored in the current context
                            return instance.get_item(item)

                            # Rule R12 <----
                    else:

                        # Condition B05/01: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
                        if ( "person.name" == item ):

                            # Condition B06/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                            if ( None == instance.get_item("person.first_name") ):

                                # Condition B07/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                                if ( None == instance.get_item("person.last_name") ):
                                    # Rule R13 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A04/01: Creating data with Faker and saving in current context / person.name /
                                    fake = Faker(localization)
                                    match item_data.get("sex"):
                                        case "f":
                                            instance.add_item(item, fake.name_female())
                                        case "m":
                                            instance.add_item(item, fake.name_male())
                                        case "d":
                                            instance.add_item(item, fake.name_nonbinary())
                                        case _:
                                            instance.add_item(item, fake.name())

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R13 <----
                                else:
                                    # Rule R14 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A04/02: Creating data with Faker and saving in current context / person.first_name /
                                    fake = Faker(localization)
                                    match item_data.get("sex"):
                                        case "f":
                                            instance.add_item(item, fake.first_name_female())
                                        case "m":
                                            instance.add_item(item, fake.first_name_male())
                                        case "d":
                                            instance.add_item(item, fake.first_name_nonbinary())
                                        case _:
                                            instance.add_item(item, fake.first_name())

                                    # Action A05: Calculate person.name  from stored individual values
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R14 <----
                            else:

                                # Condition B07/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                                if ( None == instance.get_item("person.last_name") ):
                                    # Rule R15 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A04/03: Creating data with Faker and saving in current context / person.last_name /
                                    fake = Faker(localization)
                                    match item_data.get("sex"):
                                        case "f":
                                            instance.add_item(item, fake.last_name_female())
                                        case "m":
                                            instance.add_item(item, fake.last_name_male())
                                        case "d":
                                            instance.add_item(item, fake.last_name_nonbinary())
                                        case _:
                                            instance.add_item(item, fake.last_name())

                                    # Action A05: Calculate person.name  from stored individual values
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R15 <----
                                else:
                                    # Rule R16 ---->

                                    _item_builder_engine_rule_executed = True

                                    # Action A05: Calculate person.name  from stored individual values
                                    first_name = instance.get_item("person.first_name")
                                    last_name = instance.get_item("person.last_name")
                                    instance.add_item("person.name", f"{first_name} {last_name}")

                                    # Action A06: Return of data stored in the current context
                                    return instance.get_item(item)

                                    # Rule R16 <----

                        # Condition B05/02: Requestes item code / person.first_name / A first name should be returned.
                        elif ( "person.first_name" == item ):
                            # Rule R17 ---->

                            _item_builder_engine_rule_executed = True

                            # Action A04/01: Creating data with Faker and saving in current context / person.name /
                            fake = Faker(localization)
                            match item_data.get("sex"):
                                case "f":
                                    instance.add_item(item, fake.name_female())
                                case "m":
                                    instance.add_item(item, fake.name_male())
                                case "d":
                                    instance.add_item(item, fake.name_nonbinary())
                                case _:
                                    instance.add_item(item, fake.name())

                            # Action A06: Return of data stored in the current context
                            return instance.get_item(item)

                            # Rule R17 <----

                        # Condition B05/03: Requestes item code / person.last_name / A last name should be returned.
                        elif ( "person.last_name" == item ):
                            # Rule R18 ---->

                            _item_builder_engine_rule_executed = True

                            # Action A04/03: Creating data with Faker and saving in current context / person.last_name /
                            fake = Faker(localization)
                            match item_data.get("sex"):
                                case "f":
                                    instance.add_item(item, fake.last_name_female())
                                case "m":
                                    instance.add_item(item, fake.last_name_male())
                                case "d":
                                    instance.add_item(item, fake.last_name_nonbinary())
                                case _:
                                    instance.add_item(item, fake.last_name())

                            # Action A06: Return of data stored in the current context
                            return instance.get_item(item)

                            # Rule R18 <----
                else:
                    # Rule R19 ---->

                    _item_builder_engine_rule_executed = True

                    # Action A06: Return of data stored in the current context
                    return instance.get_item(item)

                    # Rule R19 <----
        else:
            # Rule R20 ---->

            _item_builder_engine_rule_executed = True

            # Action A07: Not Implemented Yet
            pass

            # Rule R20 <----

        if not _item_builder_engine_rule_executed:

            # Error ---->
            # profile LFET.Python.Error.ini not found
            # used LF-ET 2.4.1 (260127a) build in default
            raise AssertionError("no rule executed in decision table 'ItemBuilderEngine'")
            # Error <----


# End of generated Python source code
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
