# *** WARNING: DO NOT MODIFY *** This is a generated Python source code!
#
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
# From decision table
# "../SynData/lfet/ItemBuilderEngineGermany.lfet"
# 04.02.2026 11:35
#
# Changes to this code resulting from refactorings can be synchronised
# with LF-ET using the function "Scrapbook Import".
#
# Prolog Decision Table ---->
# $$BasicIndentLevel=2
from .person import Person
import SynData

class ItemBuilderEngineGermany:

    @staticmethod
    def execute(instance: SynData, localization: str, item: str, item_data: dict):
        # Prolog Decision Table <----
        _item_builder_engine_germany_rule_executed: bool = False
        # Condition B01/01: Context is / None / There is no set context.
        if ( None == instance.Get_Context() ):
            # Condition B02/01: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
            if ( "person.name" == item ):
                # Rule R01 ---->
                _item_builder_engine_germany_rule_executed = True
                # Action A05/01: Return created data / person.name /
                return Person.get_name(item_data)
                # Rule R01 <----
            # Condition B02/02: Requestes item code / person.first_name / A first name should be returned.
            elif ( "person.first_name" == item ):
                # Rule R02 ---->
                _item_builder_engine_germany_rule_executed = True
                # Action A05/02: Return created data / person.first_name /
                return Person.get_first_name(item_data)
                # Rule R02 <----
            # Condition B02/03: Requestes item code / person.last_name / A last name should be returned.
            elif ( "person.last_name" == item ):
                # Rule R03 ---->
                _item_builder_engine_germany_rule_executed = True
                # Action A05/03: Return created data / person.last_name /
                return Person.get_last_name(item_data)
                # Rule R03 <----
        else:
            # Condition B02/01: Requestes item code / person.name / A complete name consisting of first name and last name should be returned.
            if ( "person.name" == item ):
                # Condition B03/01: Item person.first_name is / unknown / In this case the item is not known in a concrete context.
                if ( None == instance.get_item("person.first_name") ):
                    # Condition B04/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.last_name") ):
                        # Rule R04 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Action A01/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                        instance.add_item("person.first_name", Person.get_first_name(item_data))
                        # Action A02/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                        instance.add_item("person.last_name", Person.get_last_name(item_data))
                        # Action A03/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A04/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R04 <----
                    else:
                        # Rule R05 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Action A01/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                        instance.add_item("person.first_name", Person.get_first_name(item_data))
                        # Action A03/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A04/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R05 <----
                else:
                    # Condition B04/01: Item person.last_name is / unknown / In this case the item is not known in a concrete context.
                    if ( None == instance.get_item("person.last_name") ):
                        # Rule R06 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Action A02/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                        instance.add_item("person.last_name", Person.get_last_name(item_data))
                        # Action A03/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A04/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R06 <----
                    else:
                        # Rule R07 ---->
                        _item_builder_engine_germany_rule_executed = True
                        # Action A03/01: Compile person.name and add to context / person.name / Aktion ausführen
                        first_name = instance.get_item("person.first_name")
                        last_name = instance.get_item("person.last_name")
                        instance.add_item("person.name", f"{first_name} {last_name}")
                        # Action A04/01: Return Item from context / item / Aktion ausführen
                        return instance.get_item(item)
                        # Rule R07 <----
            # Condition B02/02: Requestes item code / person.first_name / A first name should be returned.
            elif ( "person.first_name" == item ):
                # Rule R08 ---->
                _item_builder_engine_germany_rule_executed = True
                # Action A01/01: Create person.first_name and add to context / person.first_name / Aktion ausführen
                instance.add_item("person.first_name", Person.get_first_name(item_data))
                # Action A04/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R08 <----
            # Condition B02/03: Requestes item code / person.last_name / A last name should be returned.
            elif ( "person.last_name" == item ):
                # Rule R09 ---->
                _item_builder_engine_germany_rule_executed = True
                # Action A02/01: Create person.last_name and add to context / person.last_name / Aktion ausführen
                instance.add_item("person.last_name", Person.get_last_name(item_data))
                # Action A04/01: Return Item from context / item / Aktion ausführen
                return instance.get_item(item)
                # Rule R09 <----

        if not _item_builder_engine_germany_rule_executed:
            # Error ---->
            # profile LFET.Python.Error.ini not found
            # used LF-ET 2.4.1 (260127a) build in default
            raise AssertionError("no rule executed in decision table 'ItemBuilderEngineGermany'")
            # Error <----

# End of generated Python source code
# Generated by LF-ET 2.4.1 (260127a), https://www.lohrfink.de/lfet
